apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample
bases:
  - ../base
resources:
  - namespace.yaml
  - deployments/mongo.yaml
  - services/mongo.yaml
configMapGenerator:
  - name: common.config
    env: configs/common.config.env
patchesJson6902:
  - path: patches/patch-ingress-hosts.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: sample-ingress-internal
  - path: patches/patch-ingress-hosts.yaml
    target:
      group: networking.k8s.io
      version: v1beta1
      kind: Ingress
      name: sample-ingress-internal-rewrite
images:
  - name: mongo
    newTag: 4.0.0
